auth0/rules

rules/add-persistent-attributes.md
rules/aspnet-webapi.md
rules/creates-lead-salesforce.md
rules/google-refresh-token.md
rules/mandrill.md
rules/roles-creation.md
rules/send-events-keenio.md
rules/send-events-segmentio.md
rules/sendgrid.md
rules/sends-sms-with-twilio.md
rules/signup.md
rules/splunk-track-event.md
rules/zapier-new-user.md

Updated rules that use persistent

---

README.md

I've just updated the rule editor image at readme to match our current dashboard's version

Updated Readme image

---

rules/creates-lead-salesforce.md

Updated SF snippet to:
* simplified error detection according to SF API specs
* Notify errors to slack

Fixed SF snippet

---

rules/mixpanel-track-event.md

Fixed rule to:
* Fix a typo on the url
* Prevent blocking rules execution until mixpanel responds

Fixed MixPanel rule

---

LICENSE
README.md

License updated to latest approved contents.
Readme includes issue reporting, author and license sections.
Fixes https://github.com/auth0/rules/issues/47

License updated and readme fixed

---

rules/guardian-multifactor.md

Add guardian-multifactor rule

---

rules/guardian-multifactor.md

In order to make dashboard work we need it
on the galery.

Add guardian-multifactor to galery

---

rules/disable-social-signup.md

Fixed a example for blocking social signups - fixed a silly typo in code.

Fixed typo - signup not singup

---

rules/link-users-by-email-with-metadata.md

"Merging metadata before linking users" sample rule.

---

rules/google-refresh-token.md

Tested with both pipeline1 and pipeline2.

Update google refresh token rule

---

rules/intercom-user.md

It'll call the Intercom API to save the contact as a new user

Adding Creates Intercom user rule

---

rules/add-attributes.md
rules/add-country.md
rules/add-income.md
rules/add-persistent-attributes.md
rules/add-roles-from-sqlserver.md
rules/appery.md
rules/aspnet-webapi.md
rules/check-domains-against-connection-aliases.md
rules/creates-box-access-token.md
rules/creates-lead-salesforce.md
rules/encrypt-sensitive-data.md
rules/facebook-custom-picture.md
rules/get-FullContact-profile.md
rules/get-getIP.md
rules/get-rapLeaf-profile.md
rules/google-service-account-token.md
rules/jwt.md
rules/linkedin-original-picture.md
rules/mixpanel-track-event.md
rules/mongodb.md
rules/parse.md
rules/pusher.md
rules/querystring.md
rules/roles-creation.md
rules/simple-whitelist-on-a-connection.md
rules/soap-webservice.md
rules/socure_fraudscore.md
rules/sso-desk-com-mutlipass.md
rules/zendesk-sso-jwt.md

P2 updates

---

rules/link-users-by-email-with-metadata.md
rules/link-users-by-email.md

Skip account linking when current user doesn't have an email

---

rules/requestbin.md

requestb.in has been shut down. New version at https://requestbin.fullcontact.com

Updated Request bin

---

README.md
src/rules/add-income.js
src/rules/add-roles-from-sqlserver.js
src/rules/appery.js
src/rules/aspnet-webapi.js
src/rules/check-domains-against-connection-aliases.js
src/rules/check-last-password-reset.js
test/rules/add-income.test.js
test/rules/add-roles-from-sqlserver.test.js
test/rules/appery.test.js
test/rules/aspnet-webapi.test.js
test/rules/check-domains-against-connection-aliases.test.js
test/rules/check-last-password-reset.test.js
test/rules/fraud-prevention-with-minfraud.test.js
test/utils/contextBuilder.js
test/utils/userBuilder.js

INTEGR8-78: Migrate batch 3 of rules

---

src/rules/facebook-custom-picture.js
src/rules/get-fullcontact-profile.js
src/rules/get-getIP.js
src/rules/get-towerdata-profile.js
src/rules/get-twitter-email.js
test/rules/add-income.test.js
test/rules/facebook-custom-picture.test.js
test/rules/get-fullcontact-profile.test.js
test/rules/get-getIP.test.js
test/rules/get-towerdata-profile.test.js
test/rules/get-twitter-email.test.js
test/utils/contextBuilder.js
test/utils/userBuilder.js

KEY-81: Migrate batch 6 of rules

---

rules.json

Updated rules.json

---

package-lock.json
rules/check-domains-against-connection-aliases.md
src/rules/check-domains-against-connection-aliases.js
test/rules/check-domains-against-connection-aliases.test.js
test/utils/contextBuilder.js

Remove API2 dependency and rely on `context.connectionOptions` to remove API2 dependency

Update the Check if user email domain matches configured domain rule

---

build
package-lock.json
package.json
schema.json
validator.js

Is that enough validation or we need to check something else?

Rules.json validator

---

src/rules/migrate-root-attributes.js

Revert "IUM-415: Enable the root attribute migration script"

---

src/rules/migrate-root-attributes.js

Revert "Revert "IUM-415: Enable the root attribute migration script""

---

src/rules/link-users-by-email-with-metadata.js

Similar to [this example](https://auth0.com/docs/link-accounts/suggested-linking#merging-metadata), use lodash.merge to avoid loss of primary user's metadata when the secondary user has no metadata. Additionally with this change, array values are merged and primary (original) user's metadata takes precedence.
This fixes #206
Create primary user with...
```
"user_metadata": {
"color": "red"
},
"app_metadata": {
"roles": [
"admin"
]
}
```
Create secondary user with...
```
"user_metadata": {
"color": "green"
},
"app_metadata": {
"roles": [
"user"
],
"foo": "bar"
}
```
Login as secondary user. Secondary user should be merged into primary user with the resulting metadata...
```
"user_metadata": {
"color": "red"
},
"app_metadata": {
"roles": [
"admin",
"user"
],
"foo": "bar"
}
```

Merge user metadata using lodash.merge

---

.circleci/config.yml

node 4 is no longer available for Auth0 Extensibility

Update test image to `node/8.11.4` and deploy from circle

---

.circleci/config.yml
package-lock.json
package.json

Changes:
- audit: bump package dependencies
- circle-ci: add node 12/13 jobs

Add Node 12/13 jobs and bump package dependencies

---

src/rules/vouched-verification.js

* update UI url to correspond with DNS change
* add change to fix `Error: secretOrPrivateKey must have a value`

small update to Vouched rule

---

src/rules/caisson-id-check.js
src/rules/iddataweb-verification-workflow.js
src/rules/mylife-digital-progressive-consent.js
src/rules/onetrust-consent-management.js
src/rules/onfido-idv.js
src/rules/scaled-access-relationships-claim.js
src/rules/vouched-verification.js

Add a link to the integration in the partner Rules.

Update partner Rule headers with a link to the integration

---

src/rules/eva-voice-biometric.js

New rule for EVA voice biometrics. Pull Request required for inclusion into Auth0 marketplace.

Add EVA voice biometrics

---

src/rules/incognia-authentication.js
src/rules/incognia-login.js

The purpose of this PR is to have the second rule template available for the Marketplace integration (Incognia). What Incognia does is to verify if the current location of the device trying to log in matches the account owner's frequent locations. This can be used as a silent 2FA for example.
This also uses the Incognia API Node Wrapper (https://www.npmjs.com/package/@incognia/api), which is not yet fully deployed to Auth0 environment. Because of this, we did not test the rule yet.

feat(incognia-authentication): including authentication rule

---

src/arengu-policy-acceptance.js

Add Arengu policy acceptance rule to Auth0's marketplace.

Add Arengu policy acceptance rule

---

src/rules/arengu-progressive-profiling.js

Add Arengu progressive profiling rule to Auth0's marketplace.

Add Arengu progressive profiling rule

---

src/rules/ip-address-allowlist.js
test/rules/ip-address-allowlist.test.js

By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.
Requested internally, renames the `ip-address-whitelist` rule to `ip-address-allowlist`.
End goal is for this auto-generated rule page (https://auth0.com/rules/ip-address-whitelist) to update with the new terminology.
> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete …

Updated ip-address-whitelist*.js to ip-address-allowlist*.js

---

.circleci/config.yml
build
package-lock.json
package.json
src/rules/incognia-authentication.js
src/rules/linkedin-original-picture.js
src/rules/mandrill.js
src/rules/mongodb.js
src/rules/parse.js
src/rules/soap-webservice.js
test/rules/access-on-weekdays-only-for-an-app.test.js
test/rules/scaled-access-relationships-claim.test.js
test/utils/load-rule.js

Update dependencies and fix issues that cropped up.

Chore: update deps
