rules/sendgrid.md
The Zendgrid API v3 change the way we need to send api keys
https://sendgrid.com/docs/Classroom/Send/api_keys.html
=> Change sendgrid request to match the new API

rules/creates-lead-salesforce.md
The first callback don't send the context  as a parameter. This can break rules workflow.
Also the rule was refactored to the following: 
* Make a fast call to the rule's callback so it won't  block waiting salesforce's to respond
* Added a few error checks to match Salesforce's API
* Moved API Keys and sensible data to configuration variables
=> Improve rule for creating leads

rules/zapier-new-user.md
Update zapier rule to:
* prevent blocking authentication on error
* use `_.extend` instead of a custom function
* Use `context.stats.loginsCount` instead of a custom attribute to detect signup
=> Updated Zapier rule

redirect-rules/simple/webtask.js
The expected Function.stringify function doesn't seem to be available in all webtask environments/configurations.
=> Use explicit here-document function

rules/jwt.md
from the `user` parameter. The `id` property that was used does not seem to exist.
=> Changed the property used for getting the user id

rules/mixpanel-track-event.md
I was working with the Tracks Logins in MixPanel rule
on the website and the callback() invocation was
throwing three errors (callback not defined,
user not defined, context not defined), and upon
invocation was failing with:
ERROR: Invalid response code from the auth0-sandbox: HTTP 400.
Unable to compile submitted JavaScript.
SyntaxError: Unexpected identifier SyntaxError: Unexpected identifier
I modified the script as in this request and it worked.
This change, if valid, will probably need to be applied to
other places as well, like the website.
=> Move callback() invocation into request.get()

rules/jwt.md
The buffer() was using variable TARGET_CLIENT_SECRET but this variable is really declared as CLIENT_SECRET.  Make a straight copy/paste fail.  Not a big deal though.
Thanks
=> remove error where TARGET_CLIENT_SECRET is undefined

rules/link-users-by-email.md
This update:
*  Uses the oldest account as the primary to provide consistency so that a oAuth user_id in Auth0 does not change from out beneath you.
*  Addresses a timing issue/bug where recently logged in user does not show up in user search results by email address.
=> handle timing bug, consistent base user_id behaivor

rules/linkedin-original-picture.md
This sets the `picture` to the original sized LinkedIn profile picture by making a call to the LinkedIn API
=> Use the original sized profile picture for LinkedIn connections

rules/duo-multifactor.md, rules/google-multifactor.md, rules/guardian-multifactor.md
There is some discussion regarding if we must change
behavior on auth0-server, but this is a workaround
to, at least, make rule behavior secure by default.
=> Uncomment ignoreCookie

redirect-rules/sms-mfa/README.md, redirect-rules/sms-mfa/mfa-passwordless.js, redirect-rules/sms-mfa/rule.js, redirect-rules/sms-mfa/webtask.js
Currently the [sms-mfa](https://github.com/auth0/rules/tree/master/redirect-rules/sms-mfa) redirect rule sample is broken for tenants that have the *OAuth2 as a Service* flag enabled, because in that mode Auth0 requires that the `state` query parameter that was passed to the redirect endpoint be passed back to Auth0 when the `/continue` endpoint is called.
This PR fixes that issue and does a little extra clean-up.
=> Add proper state parameter support to sms-mfa redirect rule

rules/splunk-HEC-track-event.md
Adds a new Splunk rule which uses Splunk's HTTP Event Collector.
@eugeniop @diegopoza
=> Splunk hec rule

rules/thisdata-alert-anomalies.md, rules/thisdata-deny-anomalies.md
These changes clarify what ThisData's two Auth0 rules do, and how they work together. Specifically
- the Prevention rule requires the Detection rule
- "Was This You?" notifications are disabled by default, and are configured
at ThisData.com
- adds ThisData to the Detection rule name, so it's easier to find
=> Improve ThisData Auth0 rule wording

rules/check_last_password_reset.md
last_password_reset is now updated whenever a password is updated, instead of at login time as it did before, so the note is no longer required.
=> Removed note about last_password_reset mechanics

rules/roles-creation.md
Check for `user.email` to be defined before using `user.email.indexOf()`. This accounts for connections that don't provide email and sets an example for doing property checks in general when customizing this rule template.
=> Check for property before using indexOf

rules/get-twitter-email.md
This prevents the rule from failing when the Twitter identity is linked
as a secondary user on a linked account.
=> Fix Get Twitter Email rule breaking on linked accounts

rules/link-users-by-email.md
We need to use `email` instead of `email.raw` or email search will be case sensitive.
However we have to filter the results since `bar-foo@baz.com` is also found when you search `foo@baz.com` as `-` is a special character.
=> Fix email matching to be case insensitive

rules/link-users-by-email-with-metadata.md
Without this change the rule is case sensitive and the emails are not being linked.
The rule as it is will be case sensitive and linking of accounts with emails like `Risco2008@live.com` (from google or live account) will not be linked with DB-Connections users `risco2008@live.com`.
Unless the field `email.raw` is used for specific purposes which I am unaware of I suggest using the `email` instead of `email.raw`.
=> Case insensitive email search bug fix proposal

rules/splunk-HEC-track-event.md
Hi,
Just a quick fix for something I encountered using the HEC rule.
Prior to this fix, a new `Tracks Logins/SignUps With Splunk HEC` rule will not compile.
=> Corrected missing semicolon on HEC track event.

rules/link-users-by-email-with-metadata.md, rules/link-users-by-email.md
If the primary account changes, previously it would cause an error (in the code flow) or an id token with the wrong sub claim (user_id). We added a mechanism to indicate the new primary user ID in a rule to fix this issue.
Customers can set the primary user ID in a rule using `context.primaryUser = 'auth0|foo123'` after account linking.
=> Fix primaryUser issue

rules/link-users-by-email-with-metadata.md, rules/link-users-by-email.md
Changes:
* Use `GET /api/v2/users-by-email` endpoint for searching users in linking rules
* Fix undefined variable issue in link-users-by-email-with-metadata rule
=> Use /users-by-email endpoint for searching users

rules/google-multifactor.md
We are deprecating (and very soon removing) support for setting totp secret key from the rule.
=> Removing deprecated key in google-authenticator rule

rules/verify-user-email-with-password-reset.md
This rule will set the user's email as verified in the next login sequence after the password is reseted successfully. ZD # 34205
=> Rule for verifying user email with password reset

rules/link-users-by-email-with-metadata.md, rules/link-users-by-email.md
Some Identity-Providers like GitHub provide a `user_id` as an integer. This breaks the assumptions of the `/identities` API. 
This patch ensures saved `user_id` is a string.
=> Accept Numeric User-IDs when linking Accounts

rules/slack.md
Fixing as per https://github.com/auth0/docs/pull/5860 :
Use case:
- User requests refresh token during sign up, hence user has registered and authenticated (context.stats.loginsCount is 1), message sent --> OK!
- User uses refresh token to authenticate (context.stats.loginsCount still is 1 since refresh token usage does not count as login), message sent --> WRONG!
Checking for context.protocol === 'oauth2-refresh-token' fixes this issue.
=> Update Slack Rule so it's not triggered by refresh token

rules/check-domains-against-connection-aliases.md, src/rules/check-domains-against-connection-aliases.js, test/rules/check-domains-against-connection-aliases.test.js
The rule template and tests have been updated to cover the following 4 scenarios:
- No `tenant_domain` and no `domain_aliases` specified -> allow access
- Tenant domain specified and no domain aliases specified -> check `tenant_domain` for match
- Tenant domain specified and domain aliases specified -> check for match in `tenant_domain` and `domain_aliases`
- No tenant domain specified and domain aliases specified -> reject (this case is odd and shouldn’t exist but we allow it via API2)
Discussed here: https://auth0.slack.com/archives/CBTDY4DJN/p1536589223000100?thread_ts=1536265487.000100&cid=CBTDY4DJN
=> Update check domains rule to account for various cases

rules/check-domains-against-connection-aliases.md, src/rules/check-domains-against-connection-aliases.js, test/rules/check-domains-against-connection-aliases.test.js
According to the spec, the following emails are valid:
- `attacker”@microsoft.com@whatever”@gmail.com`
- `"very.(),:;<>[]\".VERY.\"very@\\ \"very\".unusual"@strange.example.com`
For `attacker”@microsoft.com@whatever”@gmail.com`. The current rule would allow `microsoft.com`.
=> Protect against malicious emails

rules/mfa.md, src/rules/mfa.js, test/rules/mfa.test.js
We will support specifying `provider = 'any'` in MFA rules to let the server pick the appropriate provider based on dashboard configuration.
=> Add provider='any' rule for MFA

redirect-rules/simple/README.md
Was redirecting to rule-the-run, but should be run-the-rule
=> Update "Run the Rule" header link

src/rules/duo-multifactor.js
`admin` props are not being honored for DUO, remove them from the sample rule. A separate PR was sent to remove it from docs already: https://github.com/auth0/docs/pull/6891.
=> Remove admin property references from duo rule

README.md
HTTP links have changed due to repo structure changes breaking the README Highlighted Rules section.
https://github.com/auth0/rules/blob/master/README.md#highlighted-rules
=> Fixing broken links in readme

src/rules/access-on-weekdays-only-for-an-app.js, test/rules/access-on-weekdays-only-for-an-app.test.js
Currently, the template rule generates this error:
```
Code generated an uncaught exception: ReferenceError: Date is not defined
at /data/io/9a9b825b-0330-452d-ac73-7a70ed44bbe7/webtask.js:34:22
at fn (/data/sandbox/node_modules/auth0-authz-rules-api/node_modules/async/lib/async.js:638:34)
at Immediate._onImmediate (/data/sandbox/node_modules/auth0-authz-rules-api/node_modules/async/lib/async.js:554:34)
at processImmediate [as _immediateCallback] (timers.js:396:17)
```
Which ends up with the Rule throwing a 500 Internal Server Error.
This patch defines the `date` variable to use the `Date()` function, and then references it in the following statement. This has been tested and works as expected.
=> Fixing "Date is not defined"error

src/rules/get-towerdata-profile.js, src/rules/guardian-multifactor-authorization-extension.js, src/rules/migrate-root-attributes.js, src/rules/pusher.js, src/rules/send-events-segmentio.js, src/rules/splunk-HEC-track-event.js
Several rules contain characters in their @title attributes that are not allowed. If a user tries to create a rule from one of these templates, they receive the error: `The name of the rule. Can only contain alphanumeric characters, spaces and '-'. Can neither start nor end with '-' or spaces`. 
https://auth0team.atlassian.net/browse/ESD-2054
- [  x ] This change adds test coverage for new/changed/fixed functionality
- [  x ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ✓ ] All active GitHub checks for tests, formatting, and security are passing
- [ ✓ ] The correct base branch is being used, if not `master`
=> ESD 2054: Remove illegal characters from rule titles

rules.json
Several rules contain characters in their @title attributes that are not allowed. If a user tries to create a rule from one of these templates, they receive the error: The name of the rule. Can only contain alphanumeric characters, spaces and '-'. Can neither start nor end with '-' or spaces.
https://auth0team.atlassian.net/browse/ESD-2054
[ x ] This change adds test coverage for new/changed/fixed functionality
[ x ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
[ ✓ ] All active GitHub checks for tests, formatting, and security are passing
[ ✓ ] The correct base branch is being used, if not master
=> ESD-2054: Update rules.json to remove illegal characters from rule titles

rules.json, src/rules/track-consent.js
Adds a commented User Metadata option to set consentVersion
No new default capability added, so test coverage change is not needed.
=> Track Consent Rule - add commented ability to set version of consent given

src/rules/signals-email-confidence-score.js, src/rules/signals-ip-blacklisted.js, src/rules/signals-ip-info.js, test/rules/signals-email-confidence-score.test.js, test/rules/signals-ip-blacklisted.test.js, test/rules/signals-ip-info.test.js
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.
This PR contains three different samples about how to enrich
a user's profile or use this information for access control:
- signals-ip-info.js: enrich user_metadata with information about
the country, continent, network provider name and ASN of the IP
address of the client.
- signals-ip-blacklisted.js: enrich the user_metadata with any
existing blacklists where Auth0 Signals found the IP address of
the client.
- signals-email-confidence-score.js: enrich …
=> Sample rules using the Auth0 Signals API

package.json, src/rules/onfido-idv.js
Missing semicolon is causing warning when saving the rule after creation.
https://auth0.slack.com/archives/C013GKQR53K/p1600729720187800
=> Fix onfido missing trailing semicolon

src/rules/incognia-onboarding.js
The purpose of this PR is to have the first rule template available for the Marketplace integration (Incognia). As a prerequisite, users have to declare their home addresses during account creation. What Incognia does is to compare the location history of the device with the declared address to assess the risk of synthetic identity fraud.
This also uses the Incognia API Node Wrapper (https://www.npmjs.com/package/@incognia/api), which is not yet fully deployed to Auth0 environment. Because of this, we did not test the rule yet.
=> feat(incognia-onboarding.js): creating rule

src/rules/cumulio-add-metadata-to-tokens.js
Submitting this updated rule to default to requesting customers to use app_metadata instead of user_metadata to avoid any issues regarding user permissions.
=> Switching from user_meradata to app_metadata

src/rules/arengu-policy-acceptance.js, src/rules/arengu-progressive-profiling.js, src/rules/cumulio-add-metadata-to-tokens.js, src/rules/eva-voice-biometric.js, src/rules/iddataweb-verification-workflow.js, src/rules/incognia-authentication.js, src/rules/incognia-onboarding.js, src/rules/mylife-digital-progressive-consent.js, src/rules/onetrust-consent-management.js, src/rules/scaled-access-relationships-claim.js, src/rules/seczetta-get-risk-score.js, src/rules/yoonik-face.js
Marks all Rules that have been migrated to Actions as "unpublished" so they do not appear in the dashboard. Three Rules remain on Marketplace so those have not been changed:
https://marketplace.auth0.com/features/rules
=> [DXEC-763] Remove Rule templates that have been migrated to Actions
